// src/config/navigation.js
const NAV = {
  superadmin: [
    { label: 'Dashboard',       path: '/dashboard',                icon: '🏠' },
    { label: 'Employees',       path: '/dashboard/employees',      icon: '👥' },
    { label: 'Departments',     path: '/dashboard/departments',    icon: '🏢' },
    { label: 'Attendance',      path: '/dashboard/attendance',     icon: '📅' },
    { label: 'Leave',           path: '/dashboard/leave',          icon: '🌴' },
    { label: 'Payroll',         path: '/dashboard/payroll',        icon: '💰' },
    { label: 'Reports',         path: '/dashboard/reports',        icon: '📊' },
    { label: 'Permissions',     path: '/dashboard/permissions',    icon: '🔐' },
    { label: 'Notifications',   path: '/dashboard/notifications',  icon: '🔔' },
    { label: 'Settings',        path: '/dashboard/settings',       icon: '⚙️' },
    { label: 'System Settings', path: '/dashboard/settings/system',icon: '🛠️' },
  ],
  admin: [
    { label: 'Dashboard',       path: '/dashboard',                icon: '🏠' },
    { label: 'Employees',       path: '/dashboard/employees',      icon: '👥' },
    { label: 'Departments',     path: '/dashboard/departments',    icon: '🏢' },
    { label: 'Attendance',      path: '/dashboard/attendance',     icon: '📅' },
    { label: 'Leave',           path: '/dashboard/leave',          icon: '🌴' },
    { label: 'Payroll',         path: '/dashboard/payroll',        icon: '💰' },
    { label: 'Reports',         path: '/dashboard/reports',        icon: '📊' },
    { label: 'Permissions',     path: '/dashboard/permissions',    icon: '🔐' },
    { label: 'Notifications',   path: '/dashboard/notifications',  icon: '🔔' },
    { label: 'Settings',        path: '/dashboard/settings',       icon: '⚙️' },
    { label: 'System Settings', path: '/dashboard/settings/system',icon: '🛠️' },
  ],
  manager: [
    { label: 'Dashboard',     path: '/dashboard',               icon: '🏠' },
    { label: 'My Team',       path: '/dashboard/employees',     icon: '👥' },
    { label: 'Attendance',    path: '/dashboard/attendance',    icon: '📅' },
    { label: 'Leave',         path: '/dashboard/leave',         icon: '🌴' },
    { label: 'Reports',       path: '/dashboard/reports',       icon: '📊' },
    { label: 'Notifications', path: '/dashboard/notifications', icon: '🔔' },
    { label: 'Settings',      path: '/dashboard/settings',      icon: '⚙️' },
  ],
  hr: [
    { label: 'Dashboard',       path: '/dashboard',                icon: '🏠' },
    { label: 'Employees',       path: '/dashboard/employees',      icon: '👥' },
    { label: 'Attendance',      path: '/dashboard/attendance',     icon: '📅' },
    { label: 'Leave',           path: '/dashboard/leave',          icon: '🌴' },
    { label: 'Payroll',         path: '/dashboard/payroll',        icon: '💰' },
    { label: 'Reports',         path: '/dashboard/reports',        icon: '📊' },
    { label: 'Notifications',   path: '/dashboard/notifications',  icon: '🔔' },
    { label: 'Settings',        path: '/dashboard/settings',       icon: '⚙️' },
    { label: 'System Settings', path: '/dashboard/settings/system',icon: '🛠️' },
  ],
  employee: [
    { label: 'Dashboard',     path: '/dashboard',               icon: '🏠' },
    { label: 'Attendance',    path: '/dashboard/attendance',    icon: '📅' },
    { label: 'My Leave',      path: '/dashboard/leave',         icon: '🌴' },
    { label: 'My Payslip',    path: '/dashboard/payslip',       icon: '🧾' },
    { label: 'Notifications', path: '/dashboard/notifications', icon: '🔔' },
    { label: 'Settings',      path: '/dashboard/settings',      icon: '⚙️' },
  ],
}

export default NAV